// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUPe2y8dBoAm50T4gWBVx4Z2Xvvmzib3o',
    appId: '1:179012094628:web:50773dcc41b7af8dfab431',
    messagingSenderId: '179012094628',
    projectId: 'myecommerce1',
    authDomain: 'myecommerce1.firebaseapp.com',
    storageBucket: 'myecommerce1.firebasestorage.app',
    measurementId: 'G-KYXPF3SBYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_TgVeweXpQgzCVQ6yqld0og10BqqG8K4',
    appId: '1:179012094628:android:cde4b564483c8b53fab431',
    messagingSenderId: '179012094628',
    projectId: 'myecommerce1',
    storageBucket: 'myecommerce1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4sUtilC5q9JEoL9WuBdidkZPhr5-F7GM',
    appId: '1:179012094628:ios:cc3328f5617c3991fab431',
    messagingSenderId: '179012094628',
    projectId: 'myecommerce1',
    storageBucket: 'myecommerce1.firebasestorage.app',
    iosBundleId: 'com.example.myEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4sUtilC5q9JEoL9WuBdidkZPhr5-F7GM',
    appId: '1:179012094628:ios:cc3328f5617c3991fab431',
    messagingSenderId: '179012094628',
    projectId: 'myecommerce1',
    storageBucket: 'myecommerce1.firebasestorage.app',
    iosBundleId: 'com.example.myEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUPe2y8dBoAm50T4gWBVx4Z2Xvvmzib3o',
    appId: '1:179012094628:web:6f1a9f63fd0e215afab431',
    messagingSenderId: '179012094628',
    projectId: 'myecommerce1',
    authDomain: 'myecommerce1.firebaseapp.com',
    storageBucket: 'myecommerce1.firebasestorage.app',
    measurementId: 'G-7D6M4X3TRZ',
  );
}
